---
title: "devjugal.com"
subtitle: "Dashboard"
# logo: "logo.png"
icon: "fa-solid fa-icicles" # Optional icon

header: true
footer: '<p>crazyuploader @ <a href="https://github.com/crazyuploader">GitHub</a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
# links:
#   - name: "Contribute"
#     icon: "fab fa-github"
#     url: "https://github.com/bastienwirtz/homer"
#     target: "_blank" # optional html a tag target attribute
#   - name: "Wiki"
#     icon: "fas fa-book"
#     url: "https://www.wikipedia.org/"
# this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
# see url field and assets/additional-page.yml.dist used in this example:
#- name: "another page!"
#  icon: "fas fa-file-alt"
#  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Links"
    icon: "fas fa-cloud"
    items:
      - name: "Website"
        icon: "fas fa-globe"
        url: "https://devjugal.com"
        tag: "online"
        target: "_blank"

      - name: "TIL"
        icon: "fas fa-book"
        url: "https://til.devjugal.com"
        tag: "online"
        target: "_blank"

      - name: "Blog"
        icon: "fas fa-blog"
        url: "https://blog.devjugal.com"
        tag: "online"
        target: "_blank"

      - name: "Resume"
        icon: "fas fa-file"
        url: "https://resume.devjugal.com"
        tag: "online"
        target: "_blank"

      - name: "Social"
        icon: "fas fa-share-alt"
        url: "https://social.devjugal.com"
        tag: "online"
        target: "_blank"

  # - name: "Social"
  #   icon: "fas fa-users"
  #   items:
  #     - name: "Email"
  #       icon: "fas fa-envelope"
  #       url: "mailto:me@devjugal.com"
  #       tag: "online"

  #     - name: "GitHub"
  #       icon: "fab fa-github"
  #       url: "https://github.com/crazyuploader"
  #       tag: "online"
  #       target: "_blank"

  #     - name: "GitLab"
  #       icon: "fab fa-gitlab"
  #       url: "https://gitlab.com/crazyuploader"
  #       tag: "online"
  #       target: "_blank"

  #     - name: "Docker Hub"
  #       icon: "fab fa-docker"
  #       url: "https://hub.docker.com/u/crazyuploader"
  #       tag: "online"
  #       target: "_blank"

  #     - name: "LinkedIn"
  #       icon: "fab fa-linkedin"
  #       url: "https://www.linkedin.com/in/crazyuploader/"
  #       tag: "online"
  #       target: "_blank"

  #     - name: "Twitter"
  #       icon: "fab fa-twitter"
  #       url: "https://twitter.com/jugalkishore839"
  #       tag: "online"
  #       target: "_blank"

  #     - name: "Reddit"
  #       icon: "fab fa-reddit"
  #       url: "https://www.reddit.com/user/crazyuploader"
  #       tag: "online"
  #       target: "_blank"

  #     - name: "Telegram"
  #       icon: "fab fa-telegram"
  #       url: "https://t.me/crazyuploader"
  #       tag: "online"
  #       target: "_blank"

  - name: "Uptime"
    icon: "fas fa-clock"
    items:
      - name: "Updown"
        icon: "fas fa-up-down"
        url: "https://status.devjugal.com"
        tag: "online"
        target: "_blank"

      - name: "UptimeRobot"
        icon: "fas fa-robot"
        url: "https://stats.devjugal.com"
        tag: "online"
        target: "_blank"

  - name: "Applications on Server01"
    icon: "fas fa-server"
    items:
      - name: "API"
        tag: "self-hosted"
        icon: "fas fa-code"
        url: "https://api.devjugal.com"
        target: "_blank"

      - name: "Speedtest"
        tag: "self-hosted"
        icon: "fas fa-tachometer-alt"
        url: "https://speedtest.devjugal.com"
        target: "_blank"

      - name: "Smokeping"
        tag: "self-hosted"
        icon: "fas fa-chart-line"
        url: "https://smokeping.devjugal.com"
        target: "_blank"

      - name: "Mongo Express"
        tag: "self-hosted"
        icon: "fas fa-database"
        url: "https://mongo.devjugal.com"
        target: "_blank"

      - name: "VS Code"
        tag: "self-hosted"
        icon: "fas fa-terminal"
        url: "https://code.devjugal.com"
        target: "_blank"

      - name: "IP Address"
        tag: "self-hosted"
        icon: "fas fa-network-wired"
        url: "https://ip.devjugal.com"
        target: "_blank"

      - name: "Tools"
        tag: "self-hosted"
        icon: "fas fa-tools"
        url: "https://tools.devjugal.com"
        target: "_blank"

      - name: "Uptime"
        tag: "self-hosted"
        icon: "fas fa-clock"
        url: "https://uptime.devjugal.com"
        target: "_blank"
